### ISSUE TITLE
Add support for Boto credential profiles

### ISSUE THREAD

**Issue by jakosky** [Answers4AWS/graffiti-monkey#10]
I would like to specify which profile in my .boto file to use.

**Comment by pas256** [comment]
Based on this:
http://boto.readthedocs.org/en/latest/boto_config_tut.html

You can specify the profile to use by setting the environment variable `AWS_PROFILE`.

Is that sufficient or did you have something else in mind?

**Comment by jakosky** [comment]
So this worked, but it would be so much easier as a single line...


graffiti-monkey --region us-east-1 --profile work


...than this...


export AWS_PROFILE=work

graffiti-monkey --region us-east-1

unset AWS_PROFILE




On Wed, Mar 4, 2015 at 2:12 PM, Peter Sankauskas <notifications@github.com>
wrote:

> Based on this:
> http://boto.readthedocs.org/en/latest/boto_config_tut.html
>
> You can specify the profile to use by setting the environment variable
> AWS_PROFILE.
>
> Is that sufficient or did you have something else in mind?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Answers4AWS/graffiti-monkey/issues/10#issuecomment-77248392>
> .
>



-- 
Jay Jakosky
720.244.0137

**Comment by pas256** [comment]
Yeah I can see that. If you want to submit a PR, I'd accept it.

**Comment by pas256** [comment]
Thanks for the PR
