### ISSUE TITLE
Config file versus command line arguments

### ISSUE THREAD

**Issue by paulwakeford** [Answers4AWS/graffiti-monkey#14]
Currently if options are specified in both the config file and as command line arguments, the config file 'wins'. I think this is the wrong way around and am proposing reversing this order. 

By reversing the logic, my standard options would be in the config file, and if I want to override those options (my defaults) I use a command line argument.

This has become more of an issue now I've added support for items such as the boto profile and volume ids as command line arguments. e.g. I want my 'test' profile to be the default so I put that in the config file, but if I want to target my production account I have to edit the config file - it would be easier if I could use the command line --profile argument to override.

Thoughts on changing the primary option source to be the command line argument?

Thanks,

Paul

**Comment by pvbouwel** [comment]
To me it indeed makes sense to give preference to command line passed arguments. +1

**Comment by pas256** [comment]
I agree too. Is there a PR for this?

**Comment by pwakeford** [comment]
Nope, I was just shooting the breeze, testing the waters.
